on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: github-release,manifest
          draft-pull-request: "true"
          labels: "be-autorelease: pending"
          release-labels: "be-autorelease: tagged"