on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          package-name: release-please-action
          draft-pull-request: "true"
          pull-request-header: "This is a pull request header"
          "label": "be-autorelease: pending"
          "release-labels": "be-autorelease: tagged"