name: Test Filter Branch

on:
  pull_request:
    types: [ready_for_review]
    branches-ignore:
      - 'release-please**'

jobs:
  test-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch
        id: check-branch
        run: |
          echo "HALO"