name: Test Filter Branch

on:
  pull_request:
    - opened

jobs:
  add-code-review-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add label
        uses: christianvuerings/add-labels@v1
        with:
          labels: |
            be-code-review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}